name: 'Enforce Single Pull Request Action'
description: 'Github action that ensure a designated user only has a single PR open at any given time.'
author: 'Isaiah Moran'
inputs:
  owner:
    required: true
    description: 'The owner of the repo the action is being performed against.'
  repo:
    required: true
    description: 'The repo the action is being performed against.'
  username:
    required: true
    description: 'The username of the account we want to enforce the one PR only policy on.'
  token:
    required: false
    description: 'The github token.'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
